const CCL_REQUIREMENTS = Object.freeze({
  'I-017': 'Sign out returns to the login screen',
  'I-019': 'Classic conversation layout',
  'I-020': 'Cozy conversation layout',
  'I-021': 'Self-Managed conversation sorting',
  'I-023': 'Recent Activity conversation sorting',
  'I-024': 'Alphabetical conversation sorting',
  'I-037': 'Open Corporate Directory',
  'I-038': 'Search Corporate Directory',
  'I-042': 'Open a Corporate Directory contact card',
  'I-046': 'Remove a bookmark without leaving the room',
  'I-054': 'Mark a conversation as unread',
  'I-055': 'Mark a conversation as read',
  'I-056': 'Open the New Message flow',
  'I-058': 'Select a recipient from typeahead',
  'I-059': 'Search for a New Message recipient',
  'I-061': 'Send a new direct message',
  'I-066': 'Open the Rooms action menu',
  'I-067': 'Open Create a Room',
  'I-069': 'Create a public or private room',
  'I-070': 'Complete the Add Members room-creation step',
  'I-071': 'Open Filter Members',
  'I-072': 'Dismiss Filter Members back to Edit Members',
  'I-073': 'Use audience-filter typeaheads',
  'I-074': 'Select an audience-filter option',
  'I-075': 'Create an audience filter',
  'I-076': 'Open Browse Rooms',
  'I-078': 'Search Browse Rooms',
  'I-079': 'Open a room preview',
  'I-080': 'Join a room from preview',
  'I-081': 'Display Browse Rooms membership state',
  'I-083': 'Pin a message',
  'I-084': 'Open the pinned-message drawer',
  'I-093': 'Open Conversation Search',
  'I-094': 'Search and sort conversation messages',
  'I-095': 'Open room notification preferences',
  'I-102': 'Render a bulleted Markdown list',
  'I-103': 'Render Markdown headings',
  'I-104': 'Render Markdown emphasis',
  'I-105': 'Render a Markdown link',
  'I-106': 'Render Markdown code styling',
  'I-107': 'Render Markdown strikethrough',
  'I-113': 'Open the message long-press menu',
  'I-114': 'Add a message reaction',
  'I-115': 'Add and remove message reactions',
  'I-116': 'Use message Copy, Edit, and Delete actions',
  'I-118': 'Copy an entire message',
  'I-122': 'Edit a plaintext message',
  'I-127': 'Open Room Info as a member',
  'I-128': 'Open and edit Room Info as an admin',
  'I-129': 'Open the room member list',
  'I-130': 'Open member management as an admin',
  'I-131': 'Open member actions',
  'I-132': 'Edit room membership',
  'I-134': 'Persist room notification preferences',
  'I-141': 'Add or remove room members',
  'I-142': 'Recognize an appointment ID',
  'I-143': 'Render a valid appointment card',
  'I-144': 'Render an invalid appointment card',
  'I-157': 'Attach an image or file',
  'I-159': 'Send a GIF',
  'I-168': 'Persist an unsent message draft',
  'I-177': 'Show Corporate Events after login',
  'I-181': 'Open a Corporate Event link item',
  'I-183': 'Open a Corporate Event user DM',
  'I-184': 'Open a Corporate Event room',
  'I-188': 'Expand and collapse Corporate Events',
});

function cclRequirement(id, coverage = 'full') {
  if (!Object.hasOwn(CCL_REQUIREMENTS, id)) {
    throw new Error(`Unknown CCL requirement: ${id}`);
  }
  if (!['full', 'partial'].includes(coverage)) {
    throw new Error(`Invalid CCL coverage for ${id}: ${coverage}`);
  }
  return Object.freeze({ id, title: CCL_REQUIREMENTS[id], coverage });
}

module.exports = { CCL_REQUIREMENTS, cclRequirement };
